[package]
name = "cleanse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2.16"
color-eyre = "0.5.11"
csv = "1.1.6"
structopt = "0.3.22"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
